### ISSUE TITLE
Weird issue

### ISSUE THREAD

**Issue by rif** [vmihailenco/msgpack#39] opened 2015-07-02 08:25 UTC
I'm using msgpack format to store data in redis.

After switching to your (fast!) lib I have this weird issue: on my local machine one of many test are failing inexplicably. But the same test passes when I am running the same test suite in a docker environment. Switching back to the old msgpack lib the tests are fine in both environments.

Do you have any hints for me on where should I be looking to fix this?

**Comment by vmihailenco** [comment] 2015-07-02 11:00
Can you share the failing test? How it fails? Which "old msgpack lib" you have in mind?

**Comment by rif** [comment] 2015-07-02 11:40
Unfortunately the test is to project specific and I don't know which data gets corrupted.
I am currently using github.com/ugorji/go/codec and with this lib (referred as old lib) the tests are OK. 

I was hoping you can give me some hints regarding the difference between my works station (arch linux 64 bit) and the docker container which is debian based. It's so weird that tests pass in container but not on my work station. 

Using your lib would give us an extra speed advantage as we are doing quite a lot of encoding/decoding in our project (https://github.com/cgrates/cgrates).

**Comment by vmihailenco** [comment] 2015-07-02 12:07
Sorry, I don't have any ideas. And I very doubt that the bug is caused by differences between containers. Most likely this is a bug in the msgpack/user code.

**Comment by rif** [comment] 2015-07-02 13:56
I think I found the issue: on my local machine I have a different timezone then on the docker and somehow the time variables get converted to localtime.

What I put in: 
&{ActivationTime:2012-01-01 00:00:00 +0000 UTC RatingPlanId:EVENING FallbackKeys:[] CdrStatQueueIds:[]}

What I get out:
&{ActivationTime:2012-01-01 02:00:00 +0200 EET RatingPlanId:EVENING FallbackKeys:[] CdrStatQueueIds:[]}

Can I prevent time being converted?

**Comment by vmihailenco** [comment] 2015-07-02 14:13
Looks like ugorji's msgpack stores timezone with time. But this lib does not store timezone and Go converts time to your local timezone by default... So I see 3 ways:
1. you can change your tests to compare unix time, e.g. `tm1.Unix() == tm2.Unix()`
2. I can change msgpack.v2 to return time in UTC timezone
3. I could try to change msgpack.v2 to store timezone with time, but I would rather not do it

Thoughts?

**Comment by rif** [comment] 2015-07-02 14:45
We are using times in UTC and that means we must write some extra code when getting data out of redis to make sure the time stays in sync. 

For example this in this struct we created a starting time and we get the end time from redis, it looks like this: &{TimeStart:2012-02-27 09:50:00 +0000 UTC TimeEnd:2012-02-28 02:00:00 +0200 EET ...
Having TimeStart and TimeEnd in differet timezones does not look very good.

With this occasion I will browse the code and make sure that we always handle timezone correctly :)

I understand if you prefer not to save the timezone but we need a serialization format that does. I'll watch your project in case you decide to add it.

Thank you for your time!

**Comment by vmihailenco** [comment] 2015-07-02 15:07
>I understand if you prefer not to save the timezone

The issue is that I have to do in backwards compatible way to not break existing code. I will see what I can do.

**Comment by rif** [comment] 2015-07-02 15:32
Another issue I found while I was switching between the two libs was that I could not use the data encoded by one to load with the other :(

**Comment by vmihailenco** [comment] 2015-07-03 10:38
Both libs use custom format to store time and those formats are incompatible.

ugorji/msgpack format is documented at https://github.com/ugorji/go/blob/master/codec/time.go#L14. I would say that it is too complicated for such simple task.

vmihailenco/msgpack encodes time as a `[2]int64{tm.Unix(), tm.Nanosecond()}`.

**Comment by vmihailenco** [comment] 2017-05-11 13:39
Closing, master branch encodes time according to https://github.com/msgpack/msgpack/pull/209

**Closed by vmihailenco** 2017-05-11 13:39 UTC
